// Generated by gencpp from file drrobot_jaguar4x4_player/SetDatum.msg
// DO NOT EDIT!


#ifndef DRROBOT_JAGUAR4X4_PLAYER_MESSAGE_SETDATUM_H
#define DRROBOT_JAGUAR4X4_PLAYER_MESSAGE_SETDATUM_H

#include <ros/service_traits.h>


#include <drrobot_jaguar4x4_player/SetDatumRequest.h>
#include <drrobot_jaguar4x4_player/SetDatumResponse.h>


namespace drrobot_jaguar4x4_player
{

struct SetDatum
{

typedef SetDatumRequest Request;
typedef SetDatumResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetDatum
} // namespace drrobot_jaguar4x4_player


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::drrobot_jaguar4x4_player::SetDatum > {
  static const char* value()
  {
    return "fe903ca95d0210defda73a1629604439";
  }

  static const char* value(const ::drrobot_jaguar4x4_player::SetDatum&) { return value(); }
};

template<>
struct DataType< ::drrobot_jaguar4x4_player::SetDatum > {
  static const char* value()
  {
    return "drrobot_jaguar4x4_player/SetDatum";
  }

  static const char* value(const ::drrobot_jaguar4x4_player::SetDatum&) { return value(); }
};


// service_traits::MD5Sum< ::drrobot_jaguar4x4_player::SetDatumRequest> should match 
// service_traits::MD5Sum< ::drrobot_jaguar4x4_player::SetDatum > 
template<>
struct MD5Sum< ::drrobot_jaguar4x4_player::SetDatumRequest>
{
  static const char* value()
  {
    return MD5Sum< ::drrobot_jaguar4x4_player::SetDatum >::value();
  }
  static const char* value(const ::drrobot_jaguar4x4_player::SetDatumRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::drrobot_jaguar4x4_player::SetDatumRequest> should match 
// service_traits::DataType< ::drrobot_jaguar4x4_player::SetDatum > 
template<>
struct DataType< ::drrobot_jaguar4x4_player::SetDatumRequest>
{
  static const char* value()
  {
    return DataType< ::drrobot_jaguar4x4_player::SetDatum >::value();
  }
  static const char* value(const ::drrobot_jaguar4x4_player::SetDatumRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::drrobot_jaguar4x4_player::SetDatumResponse> should match 
// service_traits::MD5Sum< ::drrobot_jaguar4x4_player::SetDatum > 
template<>
struct MD5Sum< ::drrobot_jaguar4x4_player::SetDatumResponse>
{
  static const char* value()
  {
    return MD5Sum< ::drrobot_jaguar4x4_player::SetDatum >::value();
  }
  static const char* value(const ::drrobot_jaguar4x4_player::SetDatumResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::drrobot_jaguar4x4_player::SetDatumResponse> should match 
// service_traits::DataType< ::drrobot_jaguar4x4_player::SetDatum > 
template<>
struct DataType< ::drrobot_jaguar4x4_player::SetDatumResponse>
{
  static const char* value()
  {
    return DataType< ::drrobot_jaguar4x4_player::SetDatum >::value();
  }
  static const char* value(const ::drrobot_jaguar4x4_player::SetDatumResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DRROBOT_JAGUAR4X4_PLAYER_MESSAGE_SETDATUM_H
