// Generated by gencpp from file drrobot_jaguar4x4_player/SetDatumResponse.msg
// DO NOT EDIT!


#ifndef DRROBOT_JAGUAR4X4_PLAYER_MESSAGE_SETDATUMRESPONSE_H
#define DRROBOT_JAGUAR4X4_PLAYER_MESSAGE_SETDATUMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drrobot_jaguar4x4_player
{
template <class ContainerAllocator>
struct SetDatumResponse_
{
  typedef SetDatumResponse_<ContainerAllocator> Type;

  SetDatumResponse_()
    {
    }
  SetDatumResponse_(const ContainerAllocator& _alloc)
    {
    }






  typedef boost::shared_ptr< ::drrobot_jaguar4x4_player::SetDatumResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drrobot_jaguar4x4_player::SetDatumResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetDatumResponse_

typedef ::drrobot_jaguar4x4_player::SetDatumResponse_<std::allocator<void> > SetDatumResponse;

typedef boost::shared_ptr< ::drrobot_jaguar4x4_player::SetDatumResponse > SetDatumResponsePtr;
typedef boost::shared_ptr< ::drrobot_jaguar4x4_player::SetDatumResponse const> SetDatumResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drrobot_jaguar4x4_player::SetDatumResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drrobot_jaguar4x4_player::SetDatumResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace drrobot_jaguar4x4_player

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geographic_msgs': ['/home/perdziu/catkin_ws/src/geographic_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'drrobot_jaguar4x4_player': ['/home/perdziu/catkin_ws/src/drrobot_jaguar4x4_player/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::drrobot_jaguar4x4_player::SetDatumResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drrobot_jaguar4x4_player::SetDatumResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drrobot_jaguar4x4_player::SetDatumResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drrobot_jaguar4x4_player::SetDatumResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drrobot_jaguar4x4_player::SetDatumResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drrobot_jaguar4x4_player::SetDatumResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drrobot_jaguar4x4_player::SetDatumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::drrobot_jaguar4x4_player::SetDatumResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::drrobot_jaguar4x4_player::SetDatumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drrobot_jaguar4x4_player/SetDatumResponse";
  }

  static const char* value(const ::drrobot_jaguar4x4_player::SetDatumResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drrobot_jaguar4x4_player::SetDatumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::drrobot_jaguar4x4_player::SetDatumResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drrobot_jaguar4x4_player::SetDatumResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SetDatumResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drrobot_jaguar4x4_player::SetDatumResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::drrobot_jaguar4x4_player::SetDatumResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // DRROBOT_JAGUAR4X4_PLAYER_MESSAGE_SETDATUMRESPONSE_H
