// Generated by gencpp from file drrobot_jaguar4x4_player/SetPose.msg
// DO NOT EDIT!


#ifndef DRROBOT_JAGUAR4X4_PLAYER_MESSAGE_SETPOSE_H
#define DRROBOT_JAGUAR4X4_PLAYER_MESSAGE_SETPOSE_H

#include <ros/service_traits.h>


#include <drrobot_jaguar4x4_player/SetPoseRequest.h>
#include <drrobot_jaguar4x4_player/SetPoseResponse.h>


namespace drrobot_jaguar4x4_player
{

struct SetPose
{

typedef SetPoseRequest Request;
typedef SetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPose
} // namespace drrobot_jaguar4x4_player


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::drrobot_jaguar4x4_player::SetPose > {
  static const char* value()
  {
    return "4f3e0bbe7a24e1f929488cd1970222d3";
  }

  static const char* value(const ::drrobot_jaguar4x4_player::SetPose&) { return value(); }
};

template<>
struct DataType< ::drrobot_jaguar4x4_player::SetPose > {
  static const char* value()
  {
    return "drrobot_jaguar4x4_player/SetPose";
  }

  static const char* value(const ::drrobot_jaguar4x4_player::SetPose&) { return value(); }
};


// service_traits::MD5Sum< ::drrobot_jaguar4x4_player::SetPoseRequest> should match 
// service_traits::MD5Sum< ::drrobot_jaguar4x4_player::SetPose > 
template<>
struct MD5Sum< ::drrobot_jaguar4x4_player::SetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::drrobot_jaguar4x4_player::SetPose >::value();
  }
  static const char* value(const ::drrobot_jaguar4x4_player::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::drrobot_jaguar4x4_player::SetPoseRequest> should match 
// service_traits::DataType< ::drrobot_jaguar4x4_player::SetPose > 
template<>
struct DataType< ::drrobot_jaguar4x4_player::SetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::drrobot_jaguar4x4_player::SetPose >::value();
  }
  static const char* value(const ::drrobot_jaguar4x4_player::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::drrobot_jaguar4x4_player::SetPoseResponse> should match 
// service_traits::MD5Sum< ::drrobot_jaguar4x4_player::SetPose > 
template<>
struct MD5Sum< ::drrobot_jaguar4x4_player::SetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::drrobot_jaguar4x4_player::SetPose >::value();
  }
  static const char* value(const ::drrobot_jaguar4x4_player::SetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::drrobot_jaguar4x4_player::SetPoseResponse> should match 
// service_traits::DataType< ::drrobot_jaguar4x4_player::SetPose > 
template<>
struct DataType< ::drrobot_jaguar4x4_player::SetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::drrobot_jaguar4x4_player::SetPose >::value();
  }
  static const char* value(const ::drrobot_jaguar4x4_player::SetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DRROBOT_JAGUAR4X4_PLAYER_MESSAGE_SETPOSE_H
