"""autogenerated by genpy from drrobot_jaguar4x4_player/IMUInfo.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class IMUInfo(genpy.Message):
  _md5sum = "701e9d1318413bd1e8936e4896f37226"
  _type = "drrobot_jaguar4x4_player/IMUInfo"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """# IMU Sensor information message from DrRobot Robot.

Header header    	# timestamp in the header is the time the driver
		 	# returned the data reading
#make sure below sensors on your robot or not
uint32[3] accelRawData 		#Raw accel sensor reading, 0-x, 1-y,z-2
uint32[3] gyroRawData    	#Gyro raw data
uint32[3] magRawData   		# magRaw
float32[3] accelReading		# accel sensor reading  m/s2
float32[3] gyroReading		# gyro sensor reading   rad/m


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

"""
  __slots__ = ['header','accelRawData','gyroRawData','magRawData','accelReading','gyroReading']
  _slot_types = ['std_msgs/Header','uint32[3]','uint32[3]','uint32[3]','float32[3]','float32[3]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,accelRawData,gyroRawData,magRawData,accelReading,gyroReading

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(IMUInfo, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.accelRawData is None:
        self.accelRawData = [0,0,0]
      if self.gyroRawData is None:
        self.gyroRawData = [0,0,0]
      if self.magRawData is None:
        self.magRawData = [0,0,0]
      if self.accelReading is None:
        self.accelReading = [0.,0.,0.]
      if self.gyroReading is None:
        self.gyroReading = [0.,0.,0.]
    else:
      self.header = std_msgs.msg.Header()
      self.accelRawData = [0,0,0]
      self.gyroRawData = [0,0,0]
      self.magRawData = [0,0,0]
      self.accelReading = [0.,0.,0.]
      self.gyroReading = [0.,0.,0.]

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_3I.pack(*self.accelRawData))
      buff.write(_struct_3I.pack(*self.gyroRawData))
      buff.write(_struct_3I.pack(*self.magRawData))
      buff.write(_struct_3f.pack(*self.accelReading))
      buff.write(_struct_3f.pack(*self.gyroReading))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 12
      self.accelRawData = _struct_3I.unpack(str[start:end])
      start = end
      end += 12
      self.gyroRawData = _struct_3I.unpack(str[start:end])
      start = end
      end += 12
      self.magRawData = _struct_3I.unpack(str[start:end])
      start = end
      end += 12
      self.accelReading = _struct_3f.unpack(str[start:end])
      start = end
      end += 12
      self.gyroReading = _struct_3f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(self.accelRawData.tostring())
      buff.write(self.gyroRawData.tostring())
      buff.write(self.magRawData.tostring())
      buff.write(self.accelReading.tostring())
      buff.write(self.gyroReading.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 12
      self.accelRawData = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=3)
      start = end
      end += 12
      self.gyroRawData = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=3)
      start = end
      end += 12
      self.magRawData = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=3)
      start = end
      end += 12
      self.accelReading = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 12
      self.gyroReading = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_3f = struct.Struct("<3f")
