distdir:
	cp Makefile $(distdir)/
	cp install.sh $(distdir)/

all:
	@echo
	@echo "  =========  Kompilacja zakonczona  ================="
	@echo 
	@echo "  Aby zainstalowac pakiet wykonaj:"
	@echo
	@echo "        make install"
	@echo


install:
	@echo
	@echo "  =========  Instalacja zakonczona  ================"
	@echo
	@./install.sh

clean:
